// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZtmSgR6zCp7qKBdBAPbRX1JUBXpEJZI',
    appId: '1:189515107666:web:910887276681ffc0c63e8b',
    messagingSenderId: '189515107666',
    projectId: 'learnfirebase-c4c29',
    authDomain: 'learnfirebase-c4c29.firebaseapp.com',
    storageBucket: 'learnfirebase-c4c29.appspot.com',
    measurementId: 'G-FH2T6NYS7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjiejnJA6qLdv97YHmE2NMjb3m5Fqn1r4',
    appId: '1:189515107666:android:c7da081106dea80ac63e8b',
    messagingSenderId: '189515107666',
    projectId: 'learnfirebase-c4c29',
    storageBucket: 'learnfirebase-c4c29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARqGap36CQThKq-U7_h9wVrQHjO-06Q_s',
    appId: '1:189515107666:ios:e8585df863a944cfc63e8b',
    messagingSenderId: '189515107666',
    projectId: 'learnfirebase-c4c29',
    storageBucket: 'learnfirebase-c4c29.appspot.com',
    iosBundleId: 'com.example.learnfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARqGap36CQThKq-U7_h9wVrQHjO-06Q_s',
    appId: '1:189515107666:ios:d3e79b6552d46e0fc63e8b',
    messagingSenderId: '189515107666',
    projectId: 'learnfirebase-c4c29',
    storageBucket: 'learnfirebase-c4c29.appspot.com',
    iosBundleId: 'com.example.learnfirebase.RunnerTests',
  );
}
